deploy:
  image: python:latest
  stage: deploy
  before_script:
  - pip install awscli
  script:
  - aws s3 cp ./build s3://${BUCKET_NAME} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.us-east-2.amazonaws.com
  only:
  - development